### ISSUE TITLE
Users data source + grid: users shown multiple times

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-block_dash#35] opened 2019-12-19 20:44 UTC
http://dash.bdecent.de/local/dash/dashboard.php?id=12

![image](https://user-images.githubusercontent.com/3414705/71208118-a79a9f80-22a8-11ea-910c-29fb6b8cae3e.png)

**Comment by moodledev** [comment] 2020-01-02 18:16
Duplicate of #52

**Closed** 2020-01-02 18:16 UTC
